from flask import Flask, jsonify, request
from flask_cors import CORS
import psycopg2
import os
import time
import grpc
from concurrent import futures
import threading
import json
import logging
from datetime import datetime, timezone
from werkzeug.exceptions import BadRequest
from pymongo import MongoClient
import pybreaker

# generated by protoc during image build
import queue_pb2
import queue_pb2_grpc
import stomp

app = Flask(__name__)
CORS(app)

logging.basicConfig(level=logging.INFO)

# --- MongoDB Audit Logging Setup ---
try:
    mongo_client = MongoClient(os.environ.get("MONGO_URI", "mongodb://admin:secret@mongo:27017/hospital_logs?authSource=admin"))
    audit_col = mongo_client["hospital_logs"]["audit"]
    logging.info("Connected to MongoDB for audit logging.")
except Exception as e:
    audit_col = None
    logging.warning("MongoDB not available, audit logging disabled: %s", e)

# Circuit breaker: trips after 3 consecutive Mongo failures, resets after 60 seconds
mongo_breaker = pybreaker.CircuitBreaker(
    fail_max=3,
    reset_timeout=60,
    name="MongoDB-Audit"
)


@mongo_breaker
def _insert_audit(doc):
    """Inner function wrapped by circuit breaker to insert into MongoDB."""
    audit_col.insert_one(doc)


def log_audit(action, details: dict):
    """Insert a structured audit log document into MongoDB."""
    if audit_col is None:
        return
    try:
        _insert_audit({
            "action": action,
            "timestamp": datetime.now(timezone.utc),
            "source_ip": request.remote_addr,
            **details
        })
    except pybreaker.CircuitBreakerError:
        logging.warning("[CIRCUIT BREAKER] MongoDB is unavailable - audit log skipped (circuit OPEN).")
    except Exception as e:
        logging.warning("Failed to write audit log: %s", e)


def get_db_connection(retries=5, delay=2):
    """Retry DB connection to handle Docker startup timing."""
    for _ in range(retries):
        try:
            return psycopg2.connect(
                host=os.environ.get("DB_HOST"),
                database=os.environ.get("DB_NAME"),
                user=os.environ.get("DB_USER"),
                password=os.environ.get("DB_PASS")
            )
        except psycopg2.OperationalError:
            time.sleep(delay)
    raise Exception("Database not reachable after retries")


def init_db():
    conn = get_db_connection()
    cur = conn.cursor()

    cur.execute("""
        CREATE TABLE IF NOT EXISTS appointments (
            id SERIAL PRIMARY KEY,
            patient_name VARCHAR(100) NOT NULL,
            appointment_time TIMESTAMP NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    conn.commit()
    cur.close()
    conn.close()


init_db()


@app.route("/")
def home():
    return jsonify({"message": "Hospital Server Running"})


@app.route("/book", methods=["POST"])
def book():
    # Validate JSON body and return helpful errors
    try:
        data = request.get_json(force=False)
    except BadRequest:
        logging.warning('Invalid JSON received from %s: %s', request.remote_addr, request.data)
        return jsonify({"error": "Invalid JSON"}), 400

    if not data:
        logging.warning('Missing JSON body from %s', request.remote_addr)
        return jsonify({"error": "Missing JSON body"}), 400

    name = data.get("patient_name")
    appointment_time = data.get("appointment_time")

    if not name or not appointment_time:
        logging.warning('Missing fields in JSON from %s: %s', request.remote_addr, data)
        return jsonify({"error": "Missing required fields: patient_name and appointment_time"}), 400

    conn = get_db_connection()
    cur = conn.cursor()

    cur.execute(
        "INSERT INTO appointments (patient_name, appointment_time) VALUES (%s, %s)",
        (name, appointment_time)
    )

    conn.commit()
    cur.close()
    conn.close()

    # --- Audit Log ---
    log_audit("book_appointment", {
        "patient_name": name,
        "appointment_time": appointment_time
    })

    # publish a readable, persistent message to ActiveMQ (STOMP)
    try:
        conn_stomp = stomp.Connection([(os.environ.get("ACTIVEMQ_HOST", "activemq"), 61613)])
        conn_stomp.connect(wait=True)
        message_text = f"Your appointment is booked for {name} at {appointment_time}"
        # send persistent message to the queue named `hospital_queue` so it appears in the web console
        conn_stomp.send(destination='/queue/hospital_queue', body=message_text, headers={'persistent': 'true'})
        conn_stomp.disconnect()
        logging.info('Sent STOMP message to /queue/hospital_queue: %s', message_text)
    except Exception as e:
        logging.exception('Failed to send STOMP message: %s', e)

    return jsonify({"message": "Appointment booked successfully"})


@app.route("/queue", methods=["GET"])
def queue():
    conn = get_db_connection()
    cur = conn.cursor()
    cur.execute("""
        SELECT id, patient_name, appointment_time, created_at
        FROM appointments
        ORDER BY appointment_time
    """)

    rows = cur.fetchall()
    cur.close()
    conn.close()

    appointments = [
        {
            "id": row[0],
            "patient_name": row[1],
            "appointment_time": row[2].isoformat(),
            "created_at": row[3].isoformat() if row[3] is not None else None
        }
        for row in rows
    ]

    return jsonify({
        "patients_waiting": len(appointments),
        "appointments": appointments
    })


@app.route("/admin/appointments", methods=["GET"])
def admin_appointments():
    """Return full history of appointments for admin view."""
    conn = get_db_connection()
    cur = conn.cursor()

    cur.execute("""
        SELECT id, patient_name, appointment_time, created_at
        FROM appointments
        ORDER BY created_at DESC
    """)

    rows = cur.fetchall()
    cur.close()
    conn.close()

    appointments = [
        {
            "id": row[0],
            "patient_name": row[1],
            "appointment_time": row[2].isoformat(),
            "created_at": row[3].isoformat() if row[3] is not None else None
        }
        for row in rows
    ]

    return jsonify({"appointments": appointments})


@app.route("/update/<int:appointment_id>", methods=["PUT"])
def update_appointment(appointment_id):
    data = request.json
    new_time = data.get("appointment_time")

    conn = get_db_connection()
    cur = conn.cursor()

    cur.execute(
        "UPDATE appointments SET appointment_time=%s WHERE id=%s",
        (new_time, appointment_id)
    )

    conn.commit()
    cur.close()
    conn.close()

    # --- Audit Log ---
    log_audit("update_appointment", {
        "appointment_id": appointment_id,
        "new_appointment_time": new_time
    })

    return jsonify({"status": f"Appointment {appointment_id} updated successfully"})


@app.route("/delete/<int:appointment_id>", methods=["DELETE"])
def delete_appointment(appointment_id):
    conn = get_db_connection()
    cur = conn.cursor()

    cur.execute("DELETE FROM appointments WHERE id=%s", (appointment_id,))

    conn.commit()
    cur.close()
    conn.close()

    # --- Audit Log ---
    log_audit("delete_appointment", {
        "appointment_id": appointment_id
    })

    return jsonify({"status": f"Appointment {appointment_id} deleted successfully"})


if __name__ == "__main__":
    # start gRPC server in background
    class QueueServicer(queue_pb2_grpc.QueueServiceServicer):
        def GetQueue(self, request, context):
            conn = get_db_connection()
            cur = conn.cursor()
            cur.execute("""
                SELECT id, patient_name, appointment_time, created_at
                FROM appointments
                ORDER BY appointment_time
            """)
            rows = cur.fetchall()
            cur.close()
            conn.close()

            resp = queue_pb2.QueueResponse()
            resp.patients_waiting = len(rows)
            for row in rows:
                appt = queue_pb2.Appointment(
                    id=row[0],
                    patient_name=row[1],
                    appointment_time=row[2].isoformat(),
                    created_at=row[3].isoformat() if row[3] is not None else ""
                )
                resp.appointments.append(appt)
            return resp

    def serve_grpc():
        server_grpc = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
        queue_pb2_grpc.add_QueueServiceServicer_to_server(QueueServicer(), server_grpc)
        server_grpc.add_insecure_port('[::]:50051')
        server_grpc.start()
        server_grpc.wait_for_termination()

    t = threading.Thread(target=serve_grpc, daemon=True)
    t.start()

    app.run(host="0.0.0.0", port=5000)
